name: Deploy

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-deploy:
    name: Run deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
      - uses: actions/checkout@v2

      - name: Set up Node.js
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Node.js dependencies
        run: npm i
      - name: Deploy
        uses: fregante/setup-git-user@v1
      - run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
