name: Deploy

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-deploy:
    name: Run deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Node.js dependencies
        run: npm i
      - name: Deploy
        run: |
          npm run build
          cd dist
          git init
          git config --global user.email "qrsnake@gmail.com"
          git config --global user.name "deploy-bot"
          git checkout -b main
          git add -A
          git commit -m 'deploy'

          git push -f git@github.com:qrsnake/qr-snake-front.git main:gh-pages

          cd -
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
